package com.nimbus.cashier

import org.json.JSONArray
import org.json.JSONObject
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.floor
import kotlin.math.max
import kotlin.math.min
import kotlin.math.roundToInt

/**
 * The built-in illustrations an art block draws: shapes on a 400×260
 * canvas coloured from the theme (paywall-art.json, generated by
 * cashier-cloud's scripts/art-gen.mjs — the web and iOS SDKs draw the same
 * data). Pure data and arithmetic; drawing is in PaywallArtView.
 */
internal object PaywallArt {
    const val WIDTH = 400.0
    const val HEIGHT = 260.0

    sealed class Paint {
        data class Token(val token: String) : Paint()
        data class Linear(val angle: Double, val stops: List<String>) : Paint()
    }

    data class Shape(
        val t: String,
        val x: Double? = null, val y: Double? = null, val w: Double? = null, val h: Double? = null, val r: Double? = null,
        val cx: Double? = null, val cy: Double? = null, val rx: Double? = null, val ry: Double? = null,
        val d: String? = null,
        val rot: Double? = null,
        val fill: Paint? = null,
        val stroke: String? = null,
        val sw: Double? = null,
        val blur: Double? = null,
        val anim: String? = null,
        val delay: Double? = null,
    ) {
        /** Parsed once. */
        val path: List<PathOp> by lazy { if (t == "path") path(d ?: "") else emptyList() }
    }

    /** Every illustration by name, read once. */
    val scenes: Map<String, List<Shape>> by lazy {
        try {
            val text = PaywallArt::class.java.getResourceAsStream("/com/nimbus/cashier/paywall-art.json")
                ?.bufferedReader()?.use { it.readText() } ?: return@lazy emptyMap()
            parseScenes(text)
        } catch (_: Exception) {
            emptyMap()
        }
    }

    fun parseScenes(text: String): Map<String, List<Shape>> {
        val o = JSONObject(text)
        val out = linkedMapOf<String, List<Shape>>()
        o.keys().forEach { name ->
            val arr = o.optJSONArray(name) ?: return@forEach
            out[name] = (0 until arr.length()).mapNotNull { arr.optJSONObject(it)?.let(::shape) }
        }
        return out
    }

    private fun shape(s: JSONObject): Shape {
        fun n(k: String) = (s.opt(k) as? Number)?.toDouble()
        val fill = when (val f = s.opt("fill")) {
            is String -> Paint.Token(f)
            is JSONObject -> Paint.Linear(f.optDouble("angle", 180.0), (f.optJSONArray("stops") ?: JSONArray()).let { a -> (0 until a.length()).map { a.optString(it) } })
            else -> null
        }
        return Shape(
            t = s.optString("t"), x = n("x"), y = n("y"), w = n("w"), h = n("h"), r = n("r"),
            cx = n("cx"), cy = n("cy"), rx = n("rx"), ry = n("ry"), d = s.opt("d") as? String, rot = n("rot"),
            fill = fill, stroke = s.opt("stroke") as? String, sw = n("sw"), blur = n("blur"),
            anim = s.opt("anim") as? String, delay = n("delay"),
        )
    }

    // ── Colour tokens ───────────────────────────────────────

    /** 0–255 channels (rounded, as the web draws them) and alpha. */
    data class RGBA(val r: Int, val g: Int, val b: Int, val a: Double) {
        val argb: Long get() = ((a.coerceIn(0.0, 1.0) * 255).roundToInt().toLong() shl 24) or (r.toLong() shl 16) or (g.toLong() shl 8) or b.toLong()

        /** The web's `rgba(…)` string, for comparing against it. */
        val css: String
            get() {
                val alpha = Math.round(a * 1000) / 1000.0
                val text = if (alpha == floor(alpha)) alpha.toInt().toString() else alpha.toString()
                return "rgba($r, $g, $b, $text)"
            }
    }

    private val token = Regex("""^(AT|A|T|B|S|M|#[0-9a-fA-F]{6})([+-]\d+)?(?:\*([\d.]+))?(?:@([\d.]+))?$""")

    /**
     * Resolves a token like "A+40*0.8@0.5" (base colour; hue shift in
     * degrees; HSL lightness multiplier; alpha multiplier) against the
     * palette (A, AT, T, B, S, M → hex). null is transparent.
     */
    fun color(tok: String, palette: Map<String, String>): RGBA? {
        val m = token.find(tok) ?: return null
        val name = m.groupValues[1]
        val base = if (name.startsWith("#")) name else palette[name] ?: "#000000"
        var (r, g, b, a) = rgba(base) ?: listOf(0.0, 0.0, 0.0, 1.0)
        val shift = m.groups[2]?.value?.toDoubleOrNull()
        val light = m.groups[3]?.value?.toDoubleOrNull()
        if (shift != null || light != null) {
            val (h, s, l) = hsl(r, g, b)
            val c = rgb(h + (shift ?: 0.0), s, min(1.0, max(0.0, l * (light ?: 1.0))))
            r = c[0]; g = c[1]; b = c[2]
        }
        m.groups[4]?.value?.toDoubleOrNull()?.let { a *= it }
        return RGBA(jsRound(r), jsRound(g), jsRound(b), a)
    }

    /** JavaScript's Math.round (halves up), which the web uses. */
    private fun jsRound(v: Double) = floor(v + 0.5).toInt()

    private fun rgba(hex: String): List<Double>? {
        if (!hex.startsWith("#")) return null
        var s = hex.substring(1)
        if (s.length !in listOf(3, 6, 8) || !s.all { it.isDigit() || it.lowercaseChar() in 'a'..'f' }) return null
        if (s.length == 3) s = s.map { "$it$it" }.joinToString("")
        val n = s.substring(0, 6).toLong(16)
        val a = if (s.length == 8) s.substring(6).toLong(16) / 255.0 else 1.0
        return listOf(((n shr 16) and 255).toDouble(), ((n shr 8) and 255).toDouble(), (n and 255).toDouble(), a)
    }

    private fun hsl(r0: Double, g0: Double, b0: Double): Triple<Double, Double, Double> {
        val r = r0 / 255; val g = g0 / 255; val b = b0 / 255
        val mx = maxOf(r, g, b); val mn = minOf(r, g, b); val l = (mx + mn) / 2
        if (mx == mn) return Triple(0.0, 0.0, l)
        val d = mx - mn
        val s = if (l > 0.5) d / (2 - mx - mn) else d / (mx + mn)
        val h = when (mx) {
            r -> (g - b) / d + (if (g < b) 6 else 0)
            g -> (b - r) / d + 2
            else -> (r - g) / d + 4
        }
        return Triple(h * 60, s, l)
    }

    private fun rgb(h0: Double, s: Double, l: Double): List<Double> {
        val h = ((h0 % 360) + 360) % 360 / 360
        if (s == 0.0) return listOf(l * 255, l * 255, l * 255)
        val q = if (l < 0.5) l * (1 + s) else l + s - l * s
        val p = 2 * l - q
        fun f(t0: Double): Double {
            val t = (t0 + 1) % 1
            return when {
                t < 1.0 / 6 -> p + (q - p) * 6 * t
                t < 0.5 -> q
                t < 2.0 / 3 -> p + (q - p) * (2.0 / 3 - t) * 6
                else -> p
            }
        }
        return listOf(f(h + 1.0 / 3) * 255, f(h) * 255, f(h - 1.0 / 3) * 255)
    }

    // ── Paths ───────────────────────────────────────────────

    sealed class PathOp {
        data class Move(val x: Double, val y: Double) : PathOp()
        data class Line(val x: Double, val y: Double) : PathOp()
        data class Cubic(val x1: Double, val y1: Double, val x2: Double, val y2: Double, val x: Double, val y: Double) : PathOp()
        object Close : PathOp()
    }

    /** SVG path data using M, L, C and Z with absolute coordinates. */
    fun path(d: String): List<PathOp> {
        val out = mutableListOf<PathOp>()
        val nums = mutableListOf<Double>()
        var command: Char? = null
        fun flush() {
            when (command) {
                'M' -> {
                    var i = 0
                    while (i + 1 < nums.size) {
                        // Pairs after the first are implicit line-tos, as in SVG.
                        out += if (i == 0) PathOp.Move(nums[i], nums[i + 1]) else PathOp.Line(nums[i], nums[i + 1])
                        i += 2
                    }
                }
                'L' -> {
                    var i = 0
                    while (i + 1 < nums.size) { out += PathOp.Line(nums[i], nums[i + 1]); i += 2 }
                }
                'C' -> {
                    var i = 0
                    while (i + 5 < nums.size) {
                        out += PathOp.Cubic(nums[i], nums[i + 1], nums[i + 2], nums[i + 3], nums[i + 4], nums[i + 5])
                        i += 6
                    }
                }
                'Z' -> out += PathOp.Close
                else -> {}
            }
            nums.clear()
        }
        val number = StringBuilder()
        fun endNumber() {
            number.toString().toDoubleOrNull()?.let { nums += it }
            number.clear()
        }
        for (ch in d) {
            when {
                ch in "MLCZmlcz" -> {
                    endNumber(); flush(); command = ch.uppercaseChar()
                }
                ch == '-' -> {
                    // A minus starts a new number (unless after an exponent).
                    if (number.isNotEmpty() && !number.endsWith("e")) endNumber()
                    number.append(ch)
                }
                ch.isDigit() || ch == '.' || ch == 'e' -> {
                    if (ch == '.' && number.contains('.')) endNumber()
                    number.append(ch)
                }
                else -> endNumber()
            }
        }
        endNumber()
        flush()
        return out
    }

    /** The tight bounds of path ops (cubics sampled): minX, minY, maxX, maxY. */
    fun bounds(ops: List<PathOp>): DoubleArray {
        var minX = Double.MAX_VALUE; var minY = Double.MAX_VALUE; var maxX = -Double.MAX_VALUE; var maxY = -Double.MAX_VALUE
        fun add(x: Double, y: Double) { minX = min(minX, x); minY = min(minY, y); maxX = max(maxX, x); maxY = max(maxY, y) }
        var cx = 0.0; var cy = 0.0
        for (op in ops) when (op) {
            is PathOp.Move -> { add(op.x, op.y); cx = op.x; cy = op.y }
            is PathOp.Line -> { add(op.x, op.y); cx = op.x; cy = op.y }
            is PathOp.Cubic -> {
                for (i in 0..200) {
                    val t = i / 200.0; val u = 1 - t
                    add(u * u * u * cx + 3 * u * u * t * op.x1 + 3 * u * t * t * op.x2 + t * t * t * op.x,
                        u * u * u * cy + 3 * u * u * t * op.y1 + 3 * u * t * t * op.y2 + t * t * t * op.y)
                }
                cx = op.x; cy = op.y
            }
            PathOp.Close -> {}
        }
        return doubleArrayOf(minX, minY, maxX, maxY)
    }

    /** A shape's box on the canvas (before rotation): x, y, w, h. */
    fun box(s: Shape): DoubleArray = when (s.t) {
        "rect" -> doubleArrayOf(s.x ?: 0.0, s.y ?: 0.0, s.w ?: 0.0, s.h ?: 0.0)
        "circle" -> (s.r ?: 0.0).let { r -> doubleArrayOf((s.cx ?: 0.0) - r, (s.cy ?: 0.0) - r, 2 * r, 2 * r) }
        "ellipse" -> doubleArrayOf((s.cx ?: 0.0) - (s.rx ?: 0.0), (s.cy ?: 0.0) - (s.ry ?: 0.0), 2 * (s.rx ?: 0.0), 2 * (s.ry ?: 0.0))
        "path" -> bounds(s.path).let { b -> if (b[0] > b[2]) doubleArrayOf(0.0, 0.0, 0.0, 0.0) else doubleArrayOf(b[0], b[1], b[2] - b[0], b[3] - b[1]) }
        else -> doubleArrayOf(0.0, 0.0, 0.0, 0.0)
    }

    /** Where a shape turns about: a rect's centre, else (cx, cy). */
    fun centre(s: Shape): Pair<Double, Double> =
        if (s.t == "rect") ((s.x ?: 0.0) + (s.w ?: 0.0) / 2) to ((s.y ?: 0.0) + (s.h ?: 0.0) / 2) else (s.cx ?: 0.0) to (s.cy ?: 0.0)

    // ── Motion ──────────────────────────────────────────────

    /** An `alternate` CSS animation's eased progress (0…1) at [t] seconds, after [delay]; 0 before. */
    fun swing(t: Double, duration: Double, delay: Double): Double {
        val tt = t - delay
        if (tt <= 0 || duration <= 0) return 0.0
        val cycle = tt / duration
        val n = floor(cycle)
        var p = cycle - n
        if (abs(n.toLong() % 2) == 1L) p = 1 - p
        return 0.5 - cos(PI * p) / 2
    }
}
